apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: ticketing
build:
  local:
    push: false
  artifacts:
  - image: hjcasayas/ticketing-auth
    context: auth
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - ./k8s/*
